public with sharing class ContactTriggerHandler {
 /*   private boolean m_isExecuting = false;
	private integer BatchSize = 0;

    public ContactTriggerHandler(boolean isExecuting, integer size){
		m_isExecuting = isExecuting;
		BatchSize = size;
	}
    
    public void OnAfterInsert(Contact[] newContacts){
        User U = new User();
        for(Contact newContact : newContacts){
            U.FirstName = newContact.FirstName;
            U.LastName = newContact.LastName;
            U.Email = newContact.Email;
            U.Username = newContact.User_Name__c;
            U.CommunityNickname = newContact.FirstName;
            U.Alias = newContact.FirstName;
            U.IsActive = newContact.isActive__c;
            U.TimeZoneSidKey = newContact.TimeZone__c;
            
            
            
	}
    
    
*/    

}